package star

import (
	"math/rand"
)

func calculateSpectralClass(rng *rand.Rand, star_type string) *SpectralConfig {
	classes := SpectralClasses[star_type]
	chance := rng.Float64()
	var class SpectralConfig

	total := chance
	for i := 0; i < len(classes); i++ {
		if total <= classes[i].Percent {
			class = classes[i]
			break
		}

		total += classes[i].Percent
	}

	return &class
}

type SpectralConfig struct {
	Name          string
	Type          string
	Color         string
	LuminosityMin float64 // In Solar luminosities (L☉)
	LuminosityMax float64 // In Solar luminosities (L☉)
	RadiusMin     float64 // in solar radii
	RadiusMax     float64 // in solar radii
	MassMin       float64 // in solar masses
	MassMax       float64 // in solar masses
	TempRangeMin  float64 // in K
	TempRangeMax  float64 // in K
	Percent       float64 // the % distribution of that spectral class for the specific stellar classification
	// This % is highly speculative, it is a best guess estimate from observational data and guess work
}

var SpectralClasses = map[string][]SpectralConfig{
	"O": {
		{
			Name:          "Ia/Ib",
			Type:          "Supergiant",
			Color:         "#1E90FF",
			LuminosityMin: 30_000,
			LuminosityMax: 1_000_000,
			RadiusMin:     30,
			RadiusMax:     1700,
			MassMin:       16,
			MassMax:       100,
			Percent:       0.2,
		},
		{
			Name:          "V",
			Type:          "Main Sequence",
			Color:         "#1C86EE",
			LuminosityMax: 1_000,
			LuminosityMin: 29_999,
			RadiusMin:     6,
			RadiusMax:     15,
			MassMin:       16,
			MassMax:       60,
			Percent:       0.8,
		},
	},
	"B": {
		{
			Name:          "Ia/Ib",
			Type:          "Supergiant",
			Color:         "#1E90FF",
			LuminosityMin: 30_000,
			LuminosityMax: 1_000_000,
			RadiusMin:     30,
			RadiusMax:     1700,
			MassMin:       8,
			MassMax:       25,
			Percent:       0.1,
		},
		{
			Name:          "V",
			Type:          "Main Sequence",
			Color:         "#00BFFF",
			LuminosityMin: 25,
			LuminosityMax: 25_000,
			RadiusMin:     2.5,
			RadiusMax:     6,
			MassMin:       2.1,
			MassMax:       16,
			Percent:       0.9,
		},
	},
	"A": {
		{
			Name:          "II",
			Type:          "Bright Giant",
			Color:         "#FFA500",
			LuminosityMin: 100,
			LuminosityMax: 10_000,
			RadiusMin:     3,
			RadiusMax:     10,
			MassMin:       2,
			MassMax:       10,
			Percent:       0.04,
		},
		{
			Name:          "IV",
			Type:          "Subgiant",
			Color:         "#FFD700",
			LuminosityMin: 10,
			LuminosityMax: 100,
			RadiusMin:     2,
			RadiusMax:     3,
			MassMin:       1.5,
			MassMax:       2.4,
			Percent:       0.16,
		},
		{
			Name:          "V",
			Type:          "Main Sequence",
			Color:         "#FFFFFF",
			LuminosityMin: 5,
			LuminosityMax: 50,
			RadiusMin:     1.4,
			RadiusMax:     2.5,
			MassMin:       1.4,
			MassMax:       2.4,
			Percent:       0.8,
		},
	},
	"F": {
		{
			Name:          "III",
			Type:          "Giant",
			Color:         "#FFA500",
			LuminosityMin: 10,
			LuminosityMax: 100,
			RadiusMin:     2,
			RadiusMax:     10,
			MassMin:       1.5,
			MassMax:       3.0,
			Percent:       0.05,
		},
		{
			Name:          "IV",
			Type:          "Subgiant",
			Color:         "#FFD700",
			LuminosityMin: 5,
			LuminosityMax: 10,
			RadiusMin:     1.4,
			RadiusMax:     2,
			MassMin:       1.0,
			MassMax:       1.5,
			Percent:       0.1,
		},
		{
			Name:          "V",
			Type:          "Main Sequence",
			Color:         "#F0E68C",
			LuminosityMin: 1.5,
			LuminosityMax: 5,
			RadiusMin:     1.15,
			RadiusMax:     1.4,
			MassMin:       1.0,
			MassMax:       1.4,
			Percent:       0.85,
		},
	},
	"G": {
		{
			Name:          "III",
			Type:          "Giant",
			Color:         "#FFA500",
			LuminosityMin: 10,
			LuminosityMax: 100,
			RadiusMin:     5,
			RadiusMax:     30,
			MassMin:       0.8,
			MassMax:       1.2,
			Percent:       0.1,
		},
		{
			Name:          "IV",
			Type:          "Subgiant",
			Color:         "#FFD700",
			LuminosityMin: 1,
			LuminosityMax: 5,
			RadiusMin:     1.15,
			RadiusMax:     1.4,
			MassMin:       0.8,
			MassMax:       1.1,
			Percent:       0.1,
		},
		{
			Name:          "V",
			Type:          "Main Sequence",
			Color:         "#FFFFE0",
			LuminosityMin: 0.6,
			LuminosityMax: 1.5,
			RadiusMin:     0.96,
			RadiusMax:     1.15,
			MassMin:       0.8,
			MassMax:       1.04,
			Percent:       0.8,
		},
	},
	"K": {
		{
			Name:          "Ia/Ib",
			Type:          "Supergiant",
			Color:         "#FF8C00",
			LuminosityMin: 10_000,
			LuminosityMax: 1_000_000,
			RadiusMin:     30,
			RadiusMax:     1700,
			MassMin:       3.0,
			MassMax:       8.0,
			Percent:       0.0001,
		},
		{
			Name:          "IV",
			Type:          "Subgiant",
			Color:         "#FFD700",
			LuminosityMin: 1,
			LuminosityMax: 5,
			RadiusMin:     1.15,
			RadiusMax:     1.4,
			MassMin:       0.7,
			MassMax:       1.2,
			Percent:       0.0099,
		},
		{
			Name:          "III",
			Type:          "Giant",
			Color:         "#FFA500",
			LuminosityMin: 10,
			LuminosityMax: 100,
			RadiusMin:     5,
			RadiusMax:     30,
			MassMin:       0.7,
			MassMax:       2.5,
			Percent:       0.04,
		},
		{
			Name:          "V",
			Type:          "Red Dwarfs",
			Color:         "#FFDEAD",
			LuminosityMin: 0.08,
			LuminosityMax: 0.6,
			RadiusMin:     0.45,
			RadiusMax:     0.8,
			MassMin:       0.45,
			MassMax:       0.8,
			Percent:       0.95,
		},
	},
	"M": {
		{
			Name:          "Ia/Ib",
			Type:          "Supergiant",
			Color:         "#FF4500",
			LuminosityMin: 10_000,
			LuminosityMax: 1_000_000,
			RadiusMin:     30,
			RadiusMax:     1700,
			MassMin:       0.5,
			MassMax:       2.0,
			Percent:       0.0000002,
		},
		{
			Name:          "III",
			Type:          "Giant",
			Color:         "#FFA500",
			LuminosityMin: 100,
			LuminosityMax: 10_000,
			RadiusMin:     5,
			RadiusMax:     30,
			MassMin:       0.3,
			MassMax:       0.8,
			Percent:       0.0012,
		},
		{
			Name:          "VI",
			Type:          "Subdwarf",
			Color:         "#FF6347",
			LuminosityMin: 0.00001,
			LuminosityMax: 0.0001,
			RadiusMin:     0.05,
			RadiusMax:     0.01,
			MassMin:       0.001,
			MassMax:       0.08,
			Percent:       0.0088,
		},
		{
			Name:          "V",
			Type:          "Red Dwarf",
			Color:         "#B0C4DE",
			LuminosityMin: 0.0001,
			LuminosityMax: 0.08,
			RadiusMin:     0.1,
			RadiusMax:     0.7,
			MassMin:       0.08,
			MassMax:       0.6,
			Percent:       0.99,
		},
	},
	"Brown Dwarf (L)": {
		{
			Name:          "L",
			Type:          "L-Type Brown Dwarf",
			Color:         "#FFB6C1",
			LuminosityMin: 0.0001,
			LuminosityMax: 0.001,
			RadiusMin:     0.1,
			RadiusMax:     0.15,
			MassMin:       0.012,
			MassMax:       0.075,
			TempRangeMin:  1300,
			TempRangeMax:  2400,
			Percent:       0.5,
		},
		{
			Name:          "T",
			Type:          "T-Type Brown Dwarf",
			Color:         "#87CEFA",
			LuminosityMin: 0.00001,
			LuminosityMax: 0.0001,
			RadiusMin:     0.09,
			RadiusMax:     0.1,
			MassMin:       0.012,
			MassMax:       0.075,
			TempRangeMin:  600,
			TempRangeMax:  1300,
			Percent:       0.3,
		},
		{
			Name:          "Y",
			Type:          "Y-Type Brown Dwarf",
			Color:         "#4682B4",
			LuminosityMin: 0.000001,
			LuminosityMax: 0.00001,
			RadiusMin:     0.07,
			RadiusMax:     0.09,
			MassMin:       0.012,
			MassMax:       0.075,
			TempRangeMin:  300,
			TempRangeMax:  600,
			Percent:       0.2,
		},
	},
	"White Dwarf": {
		{
			Name:          "DZ",
			Type:          "Metal-rich",
			Color:         "#A9A9A9",
			LuminosityMin: 0.001,
			LuminosityMax: 0.01,
			RadiusMin:     0.008,
			RadiusMax:     0.02,
			MassMin:       0.5,
			MassMax:       1.4,
			Percent:       0.05,
		},
		{
			Name:          "DC",
			Type:          "Carbon-oxygen",
			Color:         "#B0C4DE",
			LuminosityMin: 0.001,
			LuminosityMax: 0.01,
			RadiusMin:     0.008,
			RadiusMax:     0.02,
			MassMin:       0.5,
			MassMax:       1.4,
			Percent:       0.15,
		},
		{
			Name:          "DB",
			Type:          "Helium-rich",
			Color:         "#FFD700",
			LuminosityMin: 0.001,
			LuminosityMax: 0.01,
			RadiusMin:     0.008,
			RadiusMax:     0.02,
			MassMin:       0.5,
			MassMax:       1.4,
			Percent:       0.2,
		},
		{
			Name:          "DA",
			Type:          "Hydrogen-rich",
			Color:         "#FFFFFF",
			LuminosityMin: 0.001,
			LuminosityMax: 0.01,
			RadiusMin:     0.008,
			RadiusMax:     0.02,
			MassMin:       0.5,
			MassMax:       1.4,
			Percent:       0.6,
		},
	},
}
